import type { Metadata } from "next";
import { Share_Tech_Mono } from "next/font/google";
import GradientLayout from "@/components/background-layout";
import "./globals.css";

const shareTechMono = Share_Tech_Mono({
  weight: "400",
  variable: "--font-share-tech-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Darwis Shathibi",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",      
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${shareTechMono.className} antialiased no-scrollbar`}>
        <GradientLayout>{children}</GradientLayout>
      </body>
    </html>
  );
}
